package aoc2025.solutions

import aoc2025.solutions.Day07.solvePartOne
import org.junit.jupiter.api.Assertions.*
import kotlin.test.Test

class Day07Test {

    val testInput ="""
        .......S.......
        ...............
        .......^.......
        ...............
        ......^.^......
        ...............
        .....^.^.^.....
        ...............
        ....^.^...^....
        ...............
        ...^.^...^.^...
        ...............
        ..^...^.....^..
        ...............
        .^.^.^.^.^...^.
        ...............""".trimIndent().lines()
    @Test
    fun `Part One returns expected result`() {

        val result = solvePartOne(testInput)
        assertEquals(21, result)
    }

}