package aoc2025.solutions

import org.junit.jupiter.api.Assertions.*
import kotlin.test.Test

class Day07Test {

    val testInput ="""
        .......S.......
        ...............
        .......^.......
        ...............
        ......^.^......
        ...............
        .....^.^.^.....
        ...............
        ....^.^...^....
        ...............
        ...^.^...^.^...
        ...............
        ..^...^.....^..
        ...............
        .^.^.^.^.^...^.
        ...............""".trimIndent().lines()
    @Test
    fun `Part One returns expected result`() {

        val result = Day07.solvePartOne(testInput)
        assertEquals(21, result)
    }
    @Test
    fun `Part Two returns expected result`() {

        val result = Day07.solvePartTwo(testInput)
        assertEquals(40L, result)
    }
}